from tkinter import*
def click(event):
    global scvalue
    text = event.widget.cget("text")
    print(text)
    if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(screen.get())
        scvalue.set(value)
        screen.update()
    elif text == "C":
        scvalue.set("")
        scvalue.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
    
b = Tk()
#width x height
b.configure(background = "orange")
b.geometry("1000x1000")
#width,height
b.minsize(200,200)
put_label  = Label(text="Calculator",font = "lucida 15 bold" ,fg = "black")
scvalue = StringVar()
scvalue.set("")
screen = Entry(b,textvar = scvalue,font="lucida 40 bold",fg = "white",bg="black")
screen.pack(fill=X,ipadx=8,pady=10,padx=10)
put_label.pack()
f = Frame(b,bg="grey")
bn = Button(f,text="9",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="8",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="7",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
f.pack()
f = Frame(b,bg="grey")
bn = Button(f,text="6",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="5",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="4",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
f.pack()
f = Frame(b,bg="grey")
bn = Button(f,text="3",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="2",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="1",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
f.pack()
f = Frame(b,bg="grey")
bn = Button(f,text="0",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="-",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="*",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
f.pack()
f = Frame(b,bg="grey")
bn = Button(f,text="/",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="%",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn = Button(f,text="=",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
f.pack()
f = Frame(b,bg="grey")
bn = Button(f,text="C",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
bn.pack(side = LEFT)
bn = Button(f,text="+",padx = 8 ,pady = 10,font="lucida 35 bold")
bn.pack(side=LEFT)
bn.bind("<Button-1>",click)
f.pack()
b.mainloop()
